### ISSUE TITLE
dropdownListSelector

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/ui-kit#20]
Drop Down List Selector: 
- Is a Drop down Icon
- Is a Text aligned with the Icon
- Is a modal on click click of the Text or Icon 
- The Modal contains a list of datas separated by a divider
![image](https://user-images.githubusercontent.com/10938862/234869600-6646d99c-78ad-40bb-9c85-92c66efaceaf.png)

**Comment by pivilartisant** [comment]
merged
