### ISSUE TITLE
Create Plugin Store Card

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/ui-kit#208]
**Context**
In order to display plugins available on the plugin store, we must have a plugin store card component

![Screenshot from 2023-06-12 12-36-20](https://github.com/massalabs/ui-kit/assets/90157528/0fecb095-0a51-4af9-a37c-e7499e08bceb)

**Technical details**
We can either create a variation on the existing plugin component or create a dedicated component

**Comment by SlnPons** [comment]
On my side, I can't see the Author name.

**Comment by SlnPons** [comment]
![Image](https://github.com/massalabs/ui-kit/assets/109611779/fa25aa8c-35af-48c7-b3e8-6589ea00e938)

the composant doesn't display 80 characters but 73 ... 
We must be consistent across BE & FE. 

Is it possible to move to 80 characters?

**Comment by pivilartisant** [comment]
done https://github.com/massalabs/ui-kit/pull/251

**Comment by SlnPons** [comment]
Design is not acceptable. Please do things consciously.


![Image](https://github.com/massalabs/ui-kit/assets/109611779/358751e3-554f-4b30-b159-7f59167f0b63)
