### ISSUE TITLE
SwitchIconButton

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/ui-kit#21]
Switch Icon
- is an Icon on left
- is a text on right

- You give to the component two icons , two text and a state 
- Once click you change state , text  and icon

![image](https://user-images.githubusercontent.com/10938862/234870066-ee96fbc0-6cfa-48c5-a7e8-35236c696711.png)

**Comment by 0xMazout** [comment]
Challenge the fact that it can be only one component with this : https://github.com/massalabs/ui-kit/issues/19

Logic on parent , and re-render on switch icons

**Comment by pivilartisant** [comment]
merged
