### ISSUE TITLE
SideBarContainer

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/ui-kit#22]
Create the SideBar container component for the Wallet 
![image](https://user-images.githubusercontent.com/10938862/235095403-47eeaf95-0613-4f20-82f9-e8354ca33310.png)

Maybe we can swap this to the wallet project

**Comment by 0xMazout** [comment]
![image](https://user-images.githubusercontent.com/10938862/235095219-99067d5d-4e7d-4e85-837d-280095471faf.png)

Resize

**Comment by 0xMazout** [comment]
Hover on full deployed

**Comment by pivilartisant** [comment]
merged
