### ISSUE TITLE
Toggle Light Mode 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/ui-kit#234]
**Describe the bug**
When clicking on the light mode/dark mode toggle button, on the logo changes colors. 

**To Reproduce**

1. web/massastation 
2. npm run dev 
3. open localhost link 
4. click multiple time on the toggle 

**Expected behavior**

It should toggle on the light and dark mode correctly

**Screenshots**

https://github.com/massalabs/ui-kit/assets/90157528/b20eda45-c9f8-4ae0-b95e-83ed4ae015e0

**Comment by SlnPons** [comment]
I think this is addressed already. Can you test and confirm @LucasF243 or @mazmassa please?
Feel free to close the issue if it's done ;)

**Comment by mazmassa** [comment]
> I think this is addressed already. Can you test and confirm @LucasF243 or @mazmassa please? Feel free to close the issue if it's done ;)

We already addressed that. I have no!

**Comment by pivilartisant** [comment]
yes it has been done
