### ISSUE TITLE
TextArea

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/ui-kit#243]
**Context**
Create a component enabling the user to enter text (e.g. a description) in a given zone.

![image](https://github.com/massalabs/ui-kit/assets/72019005/a98f9050-3209-44d5-bed6-ecf5a243e4b2)

**User flow**
- go on MassaStation
- go to the "Search" page to access deployed sites 
- click on sidebar for upload a website
- enter a text in the "description"

**Time**
Predicted : 2H
Final : 3H

**Comment by SlnPons** [comment]
Love the predicted vs final time @maxime-carabina. It's great to work like this as you will see your progress days after days ;)
