### ISSUE TITLE
PrimaryButton

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/ui-kit#27]
![image](https://user-images.githubusercontent.com/72019005/236140637-e4606959-469f-4038-ac90-f28a93b479ac.png)

-it can contain an icon on the left, on the right or even both
-it can contain text
-it can change color according to the theme
-it has different states :
  - default
  - hover
  - pressed
  - disabled

**Comment by SlnPons** [comment]
Test blocked by: https://github.com/massalabs/ui-kit/pull/35

**Comment by SlnPons** [comment]
I can confirm we have a problem with the border.
