### ISSUE TITLE
SecondaryButton

### ISSUE THREAD

**Issue by maxime-carabina** [massalabs/ui-kit#28]
![image](https://user-images.githubusercontent.com/72019005/236139367-8875853c-9afd-4a60-91b3-150293413746.png)

-it can contain an icon on the left, on the right or even both
-it can contain text
-it can change color according to the theme
-it has different states :
  - default
  - hover
  - pressed
  - disabled

**Comment by SlnPons** [comment]
Test blocked by: https://github.com/massalabs/ui-kit/pull/35

**Comment by SlnPons** [comment]
LGTM, will let @LucasF243 confirm and close.
