### ISSUE TITLE
Clean colors 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/ui-kit#302]
We need to clean colors in order to remove unused values

**Comment by pivilartisant** [comment]
As of today we don't use the following colors: 
```export const colorDeepBlue = '#0F1322';
export const colorGradientDarkBlue = '#3271A5';
export const colorGradientLightBlue = '#AADBFF';```

**Comment by LucasF243** [comment]
These are the colors used on the bridge. Should they be excluded from the design system because they are in a preset? 

I don't know which is the best solution for you (recreating presets for each new project, or having the option of doing it directly in the design system)

**Comment by pivilartisant** [comment]
> These are the colors used on the bridge. Should they be excluded from the design system because they are in a preset?
> 
> I don't know which is the best solution for you (recreating presets for each new project, or having the option of doing it directly in the design system)

context about presets : we have a massa-bridge-preset.js in the bridge and a massa-station-preset.js hosted in the ui-kit
