### ISSUE TITLE
Create FAQ component 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/ui-kit#316]
<img width="682" alt="Screenshot 2023-08-07 at 11 42 54" src="https://github.com/massalabs/ui-kit/assets/90157528/52070b7a-f374-4819-96d8-1c7438b39ecd">

**Comment by pivilartisant** [comment]
Decomposed steps : 

1ere étape: tous les différents sujets sont fermés

![](https://cdn.discordapp.com/attachments/1100793048708948038/1138089224143384646/b8c11318ad8680b6ef35dc9f28e1c431.png)

 2ème quand tu cliques sur un des sujets, ça t'ouvres les différentes catégories exemple ici pour How to get tesnet tokens, ça t'ouvres genre les trois différents tokens nécessaire

![](https://cdn.discordapp.com/attachments/1100793048708948038/1138089803469041774/81dfa2d40e86fa3a8956091381891a60.png)

3ème tu clic sur une catégorie et ça t'ouvres le tuto

![](https://cdn.discordapp.com/attachments/1100793048708948038/1138090389337808896/c77682c48a02645dc3a83b0825b78cfa.png)

ça serait top si par exemple tu cliques sur une catégorie ça te ferme l'autre ou sur un sujet et ça te ferme l'autre pour éviter d'avoir un scroll à l'infini

**Comment by LucasF243** [comment]
https://www.figma.com/file/Evyy6hA4jxm4vUi3IyydRc/Bridge?type=design&node-id=2672%3A19709&mode=design&t=8rTjsvKMsePnVKxL-1
