### ISSUE TITLE
Add colors to the storybook

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/ui-kit#34]
- [x] Add the error & warning colors to the tailwing config
- [x] Display the colors used for both light and dark themes on the storybook

**Comment by SlnPons** [comment]
@mazmassa can you help me to test this please? 
I've `git pull` the latest version of the repo but can't see the colour and change the theme easily.... I probably don't know how to use the storybook / repo :/

**Comment by Pierregvx** [comment]
> @mazmassa can you help me to test this please? I've `git pull` the latest version of the repo but can't see the colour and change the theme easily.... I probably don't know how to use the storybook / repo :/

It should be here once you run the storybook
http://localhost:6006/?path=/story/colors--colors

btw should we change the the title to put it in components ?

**Comment by mazmassa** [comment]
> @Pierregvx @mazmassa it seems that the existing colours in the story book don't reflect the design system validated. I'm sure this is under control, but could you make sure to create a ticket to update them later on please ? Not a priority but just so we don't forget.

I guess @Pierregvx can deal with, right!? It's just a matter of set the missing ones and push it.
