### ISSUE TITLE
Add SVG Component

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/ui-kit#40]
**Context**
This will be a component for the following specific uses cases : 

<img width="65" alt="Screenshot 2023-05-04 at 11 02 24" src="https://user-images.githubusercontent.com/90157528/236158950-4384234d-69b6-4243-a67c-2343e5d7ce52.png">
&
<img width="63" alt="Screenshot 2023-05-04 at 11 03 40" src="https://user-images.githubusercontent.com/90157528/236159210-318149a9-9775-4c45-a12c-afff8a5433f0.png">

**How to**

- [ ] Create add SVG folder in /Icons
- [ ] Create Svg component 
- [ ] Write stories & test

**Technical Details**

The idea is to have a component with a div that will be the circle background. This background will change according to theme. 
In this div a svg image will be passed as props and rendered as child. This SVG will has a static color.

**Comment by SlnPons** [comment]
@pivilartisant I can see an error in the naming in the story book. 


![Image](https://user-images.githubusercontent.com/109611779/237056345-aaf94d60-e2a1-4f0e-8bb1-d45e256cc46e.png)

I'm not sure what is the standard but in the SVG, currently you have: 
* Massa Labs logo 
* MassaStation logo (currently named "Massa token")
Massa Labs logo will be used as a logo for the token

Can you correct this please? 
cc @mazmassa not sure how you want to handle the rework on this. Let me know if I can help :)

**Comment by mazmassa** [comment]
This is a closed MR... no idea why we are relying on that!
