### ISSUE TITLE
Improve color of toast

### ISSUE THREAD

**Issue by Thykof** [massalabs/ui-kit#406]
the text in the toast can be darkBlue and not green for better readability on white background

**Comment by pivilartisant** [comment]
You seem to be referring to the Toast.tsx component in the case of a success, which displays the color s-success set to the color : #1AE19D 
![Screenshot from 2024-05-06 11-54-06](https://github.com/massalabs/ui-kit/assets/90157528/4ea50cb8-952e-41bd-91cc-00848353135d)

**Comment by pivilartisant** [comment]
@LucasF243 can you check this out and tell us what is doable for better readability in light mode ?

**Comment by LucasF243** [comment]
text in classic color
![image](https://github.com/massalabs/ui-kit/assets/126561114/333b1b9f-2fa7-49b8-b0b3-e5677cf90e33)
